sudo: required
services:
  - docker

before_install:
  - docker build -t apoyraz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true apoyraz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-474160006183"
  bucket_path: "Docker-react"
  on:
    branch: master
  
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
